name: 'Create Tapplets Registry PR'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  package-name:
    description: 'Tapplet package name'
    required: true
    default: 'tapplet-example'
  manifest-version:
    description: 'Next version number'
    required: true
    default: '1.0.0'

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  run: node ${{ github.action_path }}/dist/index.js
  with:
    package-name: ${{ github.event.inputs.package-name }}
    manifest-version: ${{ github.event.inputs.manifest-ersion }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
