name: 'Create Tapplets Registry PR'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  release-branch-prefix:
    description:
      "The prefix of the release PR branch name, to which the release's SemVer
      version will be appended."
    default: 'release/'
    required: true
  release-type:
    description:
      'A SemVer version diff, e.g. "major", "minor", or "patch". Mutually
      exclusive with "release-version".'
    required: false
  release-version:
    description:
      'A plain SemVer version string, specifying the version to bump to.
      Mutually exclusive with "release-type".'
    required: false
  artifacts-path:
    description:
      'The path to the directory where this action will create its artifact
      files.'
    required: false
  created-pr-status:
    default: 'draft'
    description:
      'The status of the pull request when created. Allowed options are "draft"
      and "open"'
    required: true

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: 'composite'
  steps:
    - id: create-release-pr
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/create-pr.sh \
          ${{ inputs.release-version }} \
          ${{ inputs.release-branch-prefix }} \
          ${{ inputs.created-pr-status }} \
          ${{ github.actor }} \
          ${{ inputs.artifacts-path }}
