name: 'Test action'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  packageName:
    description: 'Tapplet package name'
    required: true
    default: 'tapplet-example'
  manifestVersion:
    description: 'Next version number'
    required: true
    default: '1.0.0'

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  main: dist/index.js
