name: 'Create Tapplets Registry PR'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  package-name:
    description: 'Tapplet package name'
    required: true

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  steps:
    - id: update-registry
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js

    - id: add-updated-manifest
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Register the tapplet"
        git push
