name: 'Check Tapplet'
description:
  'Check if the tapplet meets the requirements to be added to the registry'
branding:
  icon: 'check-circle'
  color: 'yellow'

inputs:
  package-name:
    description: 'The tapplet package name'
    required: true
  package-version:
    description: 'The tapplet package version'
    required: true
    default: '1.0.0'

outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  main: './dist/index.js'
