name: 'Create Tapplets Registry PR'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  package-name:
    description: 'Tapplet package name'
    default: 'tapp-example'
    required: true

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  main: './dist/index.js'
