name: 'Create Tapplets Registry PR'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'yellow'

# Define your inputs here.
inputs:
  package-name:
    description: 'Tapplet package name'
    required: true
    default: 'tapplet-example'
  package-url:
    description: 'Tapplet package https url'
    required: true
  manifest-version:
    description: 'Next version number'
    required: true
    default: '1.0.0'
  dir:
    description: 'Optional subfolder directory to save the json file. | src/ '
    required: false

# Define your outputs here.
outputs:
  status:
    description: 'Status of tapplet registration process'

runs:
  using: node20
  main: './dist/index.js'
